blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/meer-ai/meer/security/policy
    about: Please report potential security issues via the security policy.
